#!/usr/bin/expect

spawn ssh-keygen
expect "Enter file in which to save the key (/root/.ssh/id_rsa): "
send "\r"
expect "Enter passphrase (empty for no passphrase): "
send "\r"
expect "Enter same passphrase again: "
send "\r"
expect
spawn passwd
expect "Changing password for user root.\nNew password:"
send "def2ault1A\n"
expect "Retype new password:\n"
send "def2ault1A\n"
expect
spawn rm -f /usr/local/bin/sshkey_password.exp
